//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class App_SecurityEntities : DbContext
    {
        public App_SecurityEntities()
            : base("name=App_SecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app> apps { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<companyapp> companyapps { get; set; }
        public virtual DbSet<useractivity> useractivities { get; set; }
        public virtual DbSet<userinfo> userinfoes { get; set; }
        public virtual DbSet<addressmaster> addressmasters { get; set; }
    }
}
