//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carrier()
        {
            this.drivers = new HashSet<driver>();
        }
    
        public System.Guid carrierkey { get; set; }
        public string carrierid { get; set; }
        public string carriername { get; set; }
        public System.Guid addrkey { get; set; }
        public string scaccode { get; set; }
        public string licenseplate { get; set; }
        public Nullable<System.DateTime> licenseplateexpirydate { get; set; }
        public System.DateTime createdate { get; set; }
        public short status { get; set; }
        public System.DateTime statusdate { get; set; }
    
        public virtual address address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<driver> drivers { get; set; }
    }
}
