//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comment()
        {
            this.tms_orderdetailcomments = new HashSet<tms_orderdetailcomments>();
            this.tms_orderheadercomments = new HashSet<tms_orderheadercomments>();
        }
    
        public System.Guid commentkey { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.Guid> createuserkey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tms_orderdetailcomments> tms_orderdetailcomments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tms_orderheadercomments> tms_orderheadercomments { get; set; }
        public virtual document document { get; set; }
    }
}
