//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customeraddress
    {
        public System.Guid custkey { get; set; }
        public System.Guid addrkey { get; set; }
        public Nullable<short> addrtype { get; set; }
        public string addrid { get; set; }
    
        public virtual address address { get; set; }
        public virtual customer customer { get; set; }
    }
}
