//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deliveryorder()
        {
            this.dodriverdetails = new HashSet<dodriverdetail>();
            this.dodriverdetails1 = new HashSet<dodriverdetail>();
            this.invoices = new HashSet<invoice>();
            this.shipmentdetails = new HashSet<shipmentdetail>();
        }
    
        public long id { get; set; }
        public System.DateTime createdon { get; set; }
        public int status { get; set; }
        public string fbrno { get; set; }
        public Nullable<bool> isediorder { get; set; }
        public int billtoaddrid { get; set; }
        public int pickupaddrid { get; set; }
        public int consigneeaddrid { get; set; }
        public Nullable<int> returnaddrid { get; set; }
        public string brokername { get; set; }
        public string brokerrefno { get; set; }
        public string portoforigin { get; set; }
        public Nullable<decimal> shipmentweight { get; set; }
        public string freightcharges { get; set; }
        public string vesselname { get; set; }
        public string bookingno { get; set; }
        public Nullable<System.DateTime> cutoffdate { get; set; }
        public Nullable<int> boxes { get; set; }
        public string customernotes { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<long> modifiedby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dodriverdetail> dodriverdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dodriverdetail> dodriverdetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipmentdetail> shipmentdetails { get; set; }
    }
}
