//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoicedetail
    {
        public System.Guid invoicelinekey { get; set; }
        public Nullable<System.Guid> invoicekey { get; set; }
        public Nullable<System.Guid> itemkey { get; set; }
        public string description { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> extamt { get; set; }
    
        public virtual invoiceheader invoiceheader { get; set; }
        public virtual item item { get; set; }
    }
}
