//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public long id { get; set; }
        public string invoiceno { get; set; }
        public Nullable<System.DateTime> invoicedate { get; set; }
        public Nullable<long> doid { get; set; }
        public string customernotes { get; set; }
        public string exceptions { get; set; }
        public Nullable<decimal> baserate { get; set; }
        public Nullable<int> xfactor { get; set; }
        public Nullable<decimal> stopoff { get; set; }
        public Nullable<decimal> demurrage { get; set; }
        public Nullable<decimal> forklift { get; set; }
        public Nullable<decimal> incomingfreight { get; set; }
        public Nullable<decimal> outgoingfreight { get; set; }
        public Nullable<decimal> dropnpull { get; set; }
        public Nullable<decimal> overwt { get; set; }
        public Nullable<decimal> warehousestorage { get; set; }
        public Nullable<decimal> chassisfee { get; set; }
        public Nullable<decimal> overnightfee { get; set; }
        public Nullable<decimal> perdiemfee { get; set; }
        public Nullable<decimal> transloadfee { get; set; }
        public Nullable<decimal> waitingfee { get; set; }
        public Nullable<decimal> hazardousfee { get; set; }
        public Nullable<decimal> extrafee1 { get; set; }
        public Nullable<decimal> extrafee2 { get; set; }
        public Nullable<decimal> extrafee3 { get; set; }
        public Nullable<decimal> extrafee4 { get; set; }
    
        public virtual deliveryorder deliveryorder { get; set; }
    }
}
