//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceheader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoiceheader()
        {
            this.invoicedetails = new HashSet<invoicedetail>();
            this.tms_orderdetail = new HashSet<tms_orderdetail>();
        }
    
        public System.Guid invoicekey { get; set; }
        public Nullable<int> invoiceno { get; set; }
        public Nullable<System.DateTime> invoicedate { get; set; }
        public Nullable<System.Guid> custkey { get; set; }
        public Nullable<System.Guid> billtoaddrkey { get; set; }
        public Nullable<System.Guid> billtocopyaddrkey { get; set; }
        public Nullable<decimal> invoiceamount { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<short> invoicetype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoicedetail> invoicedetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tms_orderdetail> tms_orderdetail { get; set; }
    }
}
