//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipmentdetail
    {
        public long id { get; set; }
        public Nullable<long> doid { get; set; }
        public Nullable<bool> iscomplete { get; set; }
        public string containerno { get; set; }
        public string size { get; set; }
        public string seano { get; set; }
        public Nullable<System.DateTime> apptdate { get; set; }
        public Nullable<System.TimeSpan> appttime { get; set; }
        public string drivernotes { get; set; }
    
        public virtual deliveryorder deliveryorder { get; set; }
    }
}
