//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class shippingportterminal
    {
        public System.Guid terminalkey { get; set; }
        public System.Guid portkey { get; set; }
        public Nullable<System.Guid> addrkey { get; set; }
        public Nullable<short> status { get; set; }
    
        public virtual address address { get; set; }
        public virtual shippingport shippingport { get; set; }
    }
}
