//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tms_routes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tms_routes()
        {
            this.voucherheaders = new HashSet<voucherheader>();
        }
    
        public System.Guid routekey { get; set; }
        public Nullable<System.Guid> orderdetailkey { get; set; }
        public Nullable<System.Guid> orderkey { get; set; }
        public Nullable<short> legno { get; set; }
        public Nullable<short> legtype { get; set; }
        public Nullable<System.Guid> sourceaddrkey { get; set; }
        public Nullable<System.Guid> destinationaddrkey { get; set; }
        public Nullable<decimal> estimateddistanceinmiles { get; set; }
        public Nullable<decimal> estimatedtraveltime { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<System.Guid> driverkey { get; set; }
        public Nullable<System.DateTime> scheduledarrival { get; set; }
        public Nullable<System.DateTime> scheduleddeparture { get; set; }
        public Nullable<short> odometeratsource { get; set; }
        public Nullable<System.DateTime> actualarrival { get; set; }
        public Nullable<System.DateTime> actualdeparture { get; set; }
        public Nullable<short> odometeratdestination { get; set; }
    
        public virtual address address { get; set; }
        public virtual address address1 { get; set; }
        public virtual driver driver { get; set; }
        public virtual tms_orderdetail tms_orderdetail { get; set; }
        public virtual tms_orderheader tms_orderheader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voucherheader> voucherheaders { get; set; }
    }
}
