//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tms_orderheader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tms_orderheader()
        {
            this.tms_orderdetail = new HashSet<tms_orderdetail>();
            this.tms_orderheadercomments = new HashSet<tms_orderheadercomments>();
            this.tms_routes = new HashSet<tms_routes>();
            this.documents = new HashSet<document>();
        }
    
        public System.Guid orderkey { get; set; }
        public string orderno { get; set; }
        public System.DateTime orderdate { get; set; }
        public System.Guid custkey { get; set; }
        public Nullable<System.Guid> billtoaddrkey { get; set; }
        public Nullable<System.Guid> billtocopyaddrkey { get; set; }
        public Nullable<System.Guid> sourceaddrkey { get; set; }
        public Nullable<System.Guid> sourcecopyaddrkey { get; set; }
        public Nullable<System.Guid> destinationaddrkey { get; set; }
        public Nullable<System.Guid> destinationcopyaddrkey { get; set; }
        public Nullable<System.Guid> returnaddrkey { get; set; }
        public Nullable<System.Guid> returncopyaddrkey { get; set; }
        public Nullable<short> source { get; set; }
        public Nullable<short> ordertype { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<System.DateTime> statusdate { get; set; }
        public Nullable<short> holdreason { get; set; }
        public Nullable<System.DateTime> holddate { get; set; }
        public Nullable<System.Guid> brokerkey { get; set; }
        public string brokerrefno { get; set; }
        public Nullable<System.Guid> portoforiginkey { get; set; }
        public Nullable<System.Guid> carrierkey { get; set; }
        public string vesselname { get; set; }
        public string billoflading { get; set; }
        public string bookingno { get; set; }
        public Nullable<System.DateTime> cutoffdate { get; set; }
        public Nullable<short> priority { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.Guid> createuserkey { get; set; }
        public Nullable<System.DateTime> lastupdatedate { get; set; }
        public Nullable<System.Guid> lastupdateuserkey { get; set; }
    
        public virtual address address { get; set; }
        public virtual address address1 { get; set; }
        public virtual address address2 { get; set; }
        public virtual address address3 { get; set; }
        public virtual address address4 { get; set; }
        public virtual address address5 { get; set; }
        public virtual address address6 { get; set; }
        public virtual address address7 { get; set; }
        public virtual customer customer { get; set; }
        public virtual tms_holdreason tms_holdreason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tms_orderdetail> tms_orderdetail { get; set; }
        public virtual tms_ordersource tms_ordersource { get; set; }
        public virtual tms_orderstatus tms_orderstatus { get; set; }
        public virtual tms_ordertype tms_ordertype { get; set; }
        public virtual tms_priority tms_priority { get; set; }
        public virtual tms_priority tms_priority1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tms_orderheadercomments> tms_orderheadercomments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tms_routes> tms_routes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document> documents { get; set; }
    }
}
