//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tms_orderdetailcomments
    {
        public System.Guid orderdetailkey { get; set; }
        public System.Guid commentkey { get; set; }
        public Nullable<short> commenttype { get; set; }
    
        public virtual comment comment { get; set; }
        public virtual tms_orderdetail tms_orderdetail { get; set; }
    }
}
