//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucherheader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voucherheader()
        {
            this.voucherdetails = new HashSet<voucherdetail>();
            this.tms_routes = new HashSet<tms_routes>();
        }
    
        public System.Guid voucherkey { get; set; }
        public Nullable<int> voucherno { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public Nullable<System.Guid> vendkey { get; set; }
        public Nullable<System.Guid> billtoaddrkey { get; set; }
        public Nullable<System.Guid> billtocopyaddrkey { get; set; }
        public Nullable<decimal> voucheramount { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<bool> ispaymentapproved { get; set; }
    
        public virtual vendor vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voucherdetail> voucherdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tms_routes> tms_routes { get; set; }
    }
}
